[package]
name = "web-scraper-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "1.0.9"
reqwest = { version = "0.11.26", features = ["blocking"] }
scraper = "0.19.0"
